twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        issuer: '@App\Invoice\IssuerProfileProvider'
        brand_name: '%env(APP_BRAND_NAME)%'
        product_name: 'Ubytovadlo'
        product_url: 'https://ubytovadlo.cz'
        product_repo_url: 'https://github.com/vzoha/ubytovadlo'

when@test:
    twig:
        strict_variables: true
